# XQ Records Database Container
FROM postgres:18-alpine

ENV POSTGRES_DB=xq-records
ENV POSTGRES_USER=xq_records_user
ENV POSTGRES_PASSWORD=xq_records_password
ENV POSTGRES_APP_USER=xq_records_app_user
ENV POSTGRES_APP_PASSWORD=xq_records_app_password

# Generated by scripts/prepare-docker-init.sh:
#   01-prisma-migrations.sql
#   02-setup-app-user.sh (reuses scripts/create-app-user-neon.sql and grant-permissions-neon.sql)
COPY docker-init/ /docker-entrypoint-initdb.d/

EXPOSE 5432

HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=3 \
  CMD pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1