#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MIGRATIONS_DIR="$PROJECT_DIR/prisma/migrations"
DOCKER_INIT_DIR="$PROJECT_DIR/docker-init"
OUTPUT_FILE="$DOCKER_INIT_DIR/01-prisma-migrations.sql"

mkdir -p "$DOCKER_INIT_DIR"

{
  echo "-- Generated by scripts/prepare-docker-init.sh"
  echo "-- Source of truth: prisma/migrations/*/migration.sql"
  echo "-- This file initializes the local/test Docker image only."
  echo
  find "$MIGRATIONS_DIR" -mindepth 2 -maxdepth 2 -name "migration.sql" | sort | while read -r migration_file; do
    migration_name="$(basename "$(dirname "$migration_file")")"
    echo "-- >>> BEGIN Prisma migration: $migration_name"
    cat "$migration_file"
    echo
    echo "-- <<< END Prisma migration: $migration_name"
    echo
  done
} > "$OUTPUT_FILE"

echo "Prepared Docker init SQL: $OUTPUT_FILE"
